package extend.testModule;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JPanel;
import java.awt.FlowLayout;

/**
 *
 * @author pawel
 */
public class FinishPanel extends javax.swing.JPanel {
    /**
     * Creates new form FinishPanel
     */
    public FinishPanel() {
        initComponents();
        endMessageup.setText("                   Test is done.                           ");
        
        endMessageDown.setText("Try back to learning mode for increase your skill");
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endMessageup = new javax.swing.JLabel();
        endMessageCenter = new javax.swing.JLabel();
        endMessageDown = new javax.swing.JLabel();
        
        endMessageup.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        endMessageup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endMessageup.setText("                   Test is done.                           ");
        endMessageup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        endMessageCenter.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        endMessageCenter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endMessageCenter.setText("");
        endMessageCenter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        endMessageDown.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        endMessageDown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endMessageDown.setText("");
        endMessageDown.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        
        JPanel buttonPanel = new JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(21)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(endMessageCenter, GroupLayout.PREFERRED_SIZE, 441, GroupLayout.PREFERRED_SIZE)
        						.addComponent(endMessageDown, GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        						.addComponent(endMessageup, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(148)
        					.addComponent(buttonPanel, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(50)
        			.addComponent(endMessageup)
        			.addGap(18)
        			.addComponent(endMessageCenter)
        			.addGap(26)
        			.addComponent(endMessageDown)
        			.addGap(54)
        			.addComponent(buttonPanel, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(75, Short.MAX_VALUE))
        );
        buttonPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        buttonPanel.add(Tester.exitFinalBtn);
        
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents
    
    public void callFuzzy() {
    	endMessageCenter.setText("Your result is : "+this.goodAnswears+"/"+this.wordsCount);
    	new FuzzyLogic(difficult, wordsCount, goodAnswears);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel endMessageCenter;
    private javax.swing.JLabel endMessageDown;
    private javax.swing.JLabel endMessageup;
    public String filePath;
    public String difficult;
    public int wordsCount;
    public int goodAnswears;
}
