package extend.testModule;


import java.awt.Dimension;
import java.awt.FlowLayout;

/**
 *
 * @author pawel
 */
public class Tester extends javax.swing.JFrame {

    StartPanel firstPanel = new StartPanel();
    TestPanel testPanel = new TestPanel();
    FinishPanel lastPanel = new FinishPanel();
    private final int width =600;
    private final int height = 400;
    private final Dimension sizeFrame = new Dimension(width, height);
    private final Dimension sizePanel = new Dimension(500 , 500);
    /**
     * Creates new form Tester
     */
    public Tester() {
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setPreferredSize(sizeFrame);
        setResizable(false);
        this.setLocation(300,100);
        firstPanel.getSize(sizePanel);
        testPanel.setSize(sizePanel);
        firstPanel.setVisible(true);
        testPanel.setVisible(false);
        lastPanel.setVisible(false);
        add(firstPanel);
        add(testPanel);
        add(lastPanel);
        
        this.setLayout(new FlowLayout(FlowLayout.CENTER));
        
        pack();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));
        setVisible(true);

        pack();
    }
}
