package extend.testModule;


import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.event.AncestorListener;

import app.WindowOne;

/**
 *
 * @author pawel
 */
public class Tester extends javax.swing.JFrame implements ActionListener{

    
    /**
     * 
     */
    public static ActionListener listener;
	/**
     * 
     */
    public String u;
	StartPanel firstPanel ;
    TestPanel testPanel = new TestPanel();
    FinishPanel lastPanel = new FinishPanel();
    private final int width =600;
    private final int height = 400;
    private final Dimension sizeFrame = new Dimension(width, height);
    private final Dimension sizePanel = new Dimension(500 , 500);
    
    /**
     * Button for close test module from first welcome panel.
     */
    public static JButton exitBtn = new JButton("EXIT");
    
    /**
     * BUtton for close test module from finished panel.
     */
    public static JButton exitFinalBtn = new JButton("EXIT");
    /**
     * Button for starting test module.
     */
    public static JButton startBtn = new JButton("START");
    
    /**
     * Creates new form Tester
     * @param user 
     */
    public Tester(String user) {
        
    	this.u = user;
    	
    	firstPanel = new StartPanel(u);
    	
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setPreferredSize(sizeFrame);
        setResizable(false);
        this.setLocation(300,100);
        firstPanel.getSize(sizePanel);
        testPanel.setSize(sizePanel);
        firstPanel.setVisible(true);
        testPanel.setVisible(false);
        lastPanel.setVisible(false);
        this.add(firstPanel);
        this.add(testPanel);
        this.add(lastPanel);
        
        
        this.setLayout(new FlowLayout(FlowLayout.CENTER));
        
        pack();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        //setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));
        exitBtn.addActionListener(this);
        startBtn.addActionListener(this);
        exitFinalBtn.addActionListener(this);
        setVisible(true);
        

        pack();
    }

	@Override
	public void actionPerformed(ActionEvent e) {
		
		if(e.getSource() == startBtn) {
			firstPanel.setVisible(false);
			testPanel.setVisible(true);
			
		}
		if(e.getSource() == exitBtn || e.getSource() == exitFinalBtn) {
		System.out.println("button EXIT pressed.");
		WindowOne win = new WindowOne(u);
		win.setVisible(true);
		this.dispose();
		}
		
		
	}
}
